# Generated by Django 5.1.1 on 2024-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=32)),
                ('Variant', models.CharField(max_length=32)),
                ('Processor', models.CharField(max_length=32)),
                ('Ram', models.IntegerField()),
                ('Rom', models.FloatField()),
            ],
        ),
    ]
