# Generated by Django 5.1.1 on 2024-09-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Processor',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Ram',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Rom',
            new_name='rom',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Variant',
            new_name='variant',
        ),
    ]
